excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Pods

disabled_rules:
  - identifier_name
  - opening_brace

force_cast: warning
#force_try: warning

line_length:
  warning: 120
  error: 500
file_length:
  warning: 500
  error: 1200
cyclomatic_complexity:
  warning: 10
  error: 30
